### GET
GET http://localhost:3000/ HTTP/1.1

### POST 
POST http://localhost:3000/ HTTP/1.1

### GET posts
GET http://localhost:3000/posts HTTP/1.1

### GET posts id=1
GET http://localhost:3000/posts/1 HTTP/1.1

### GET posts id=1
GET http://localhost:3000/posts?id=1

###

POST http://localhost:3000/posts HTTP/1.1
content-type: application/json

{
    "title": "json-server is fun!!",
    "author": "typicode"
}
###
